"""empty message

Revision ID: 181471ef3dff
Revises: ab0378013449
Create Date: 2024-07-27 00:30:49.245095

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '181471ef3dff'
down_revision = 'ab0378013449'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('conversation_data')
        batch_op.drop_column('conversation_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conversation_id', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('conversation_data', sqlite.JSON(), nullable=False))

    # ### end Alembic commands ###
