"""empty message

Revision ID: 208eb74f9efd
Revises: 7c761326c5b8
Create Date: 2024-07-31 14:41:38.116603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '208eb74f9efd'
down_revision = '7c761326c5b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
