"""empty message

Revision ID: 2b4ef5090873
Revises: bdef6af48b2d
Create Date: 2024-07-25 18:48:56.057255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b4ef5090873'
down_revision = 'bdef6af48b2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder',
    sa.Column('reminder_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('medication_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['medication_id'], ['medication.medication_id'], ),
    sa.PrimaryKeyConstraint('reminder_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reminder')
    # ### end Alembic commands ###
