"""empty message

Revision ID: 45c9e71ca581
Revises: 67ed17c97320
Create Date: 2024-08-05 23:23:38.684138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45c9e71ca581'
down_revision = '67ed17c97320'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescription', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'medication', ['medication_id'], ['medication_id'])
        batch_op.drop_column('dosage')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dosage', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
