"""empty message

Revision ID: bb46bc1b6452
Revises: 182c23d73c19
Create Date: 2024-07-18 17:03:51.576999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb46bc1b6452'
down_revision = '182c23d73c19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.alter_column('patient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('doctor_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medical_history', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('medical_history')

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.alter_column('doctor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('patient_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
