"""empty message

Revision ID: d40d0d1d188c
Revises: d56e40a83ef6
Create Date: 2024-08-08 01:11:55.935850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd40d0d1d188c'
down_revision = 'd56e40a83ef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.alter_column('dob',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('dob',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
